apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-novation-menu-com
  namespace: kubetest
spec:
  secretName: auth-novation-menu-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: auth.novation-menu.com
  dnsNames:
  - auth.novation-menu.com